version: '3.8'

services:
  minha-banda-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Passa a vari√°vel do host (.env ou sistema) para o Docker build
        - API_KEY=${API_KEY}
    container_name: minha-banda-container
    ports:
      - "8000:80"
    restart: unless-stopped